name: engine-wasm
on:
  push:
  pull_request:
jobs:
  emscripten:
    runs-on: "ubuntu-22.04"
    name: web
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Emsdk
        uses: mymindstorm/setup-emsdk@v11
      - name: Build
        run: |
          cd build/engine-wasm
          make
          tar czf engine-wasm.tar.gz html
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: engine-wasm.tar.gz
          path: build/engine-wasm/engine-wasm.tar.gz
