name: engine-macos
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd build/engine-macos
	  make build-only
