name: engine-macos
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd build/engine-macos
          wget https://suika2.com/dl/libroot-mac.tar.gz
          tar xzf libroot-mac.tar.gz
          xcodebuild -target suika -project suika.xcodeproj -configuration Debug build
