name: engine-windows-arm64
on:
  push:
  pull_request:
jobs:
  linux:
    runs-on: "ubuntu-22.04"
    name: windows
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          cd build/engine-windows-arm64
          ./build-libs.sh
          make
          make install
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: suika-arm64.exe
          path: suika-arm64.exe
