name: suika-mac-replay
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd build/macos
          wget https://suika2.com/dl/libroot-mac.tar.gz
          tar xzf libroot-mac.tar.gz
          xcodebuild -target suika-replay -project suika.xcodeproj -configuration Debug build
