name: suika-testcases
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libx11-dev libxpm-dev mesa-common-dev xvfb lcov
          pip3 install opencv-python numpy
          make test
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: suika-test-report
          path: build/linux-x86_64-replay/lcovoutput
